spring:
  data:
    mongodb:
      username: kyalo
      password: kyalo
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.kyalo.ecommerce.kafka.OrderConfirmation, paymentConfirmation:com.kyalo.ecommerce.notification.PaymentNotificationRequest
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: kyalo
    password: kyalo
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040